name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
      - name: Build
        run: |
          python3 -m venv .venv
          source ./.venv/bin/activate
          pip install -e ./
          sh ./build_linux.sh
      - name: Zipping
        run: |
          echo "Zipping to Blender_Launcher_${{ env.RELEASE_VERSION }}_Ubuntu_x64.zip"
          cd ./dist/release/
          zip Blender_Launcher_${{ env.RELEASE_VERSION }}_Ubuntu_x64.zip "./Blender Launcher"
      - name: Archive zipfile
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Ubuntu-build
          files: dist/release/Blender_Launcher_${{ env.RELEASE_VERSION }}_Ubuntu_x64.zip
          retention-days: 4
